imports:
    - php

tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.
    # disable copy paste detector and similarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_sim: false
    php_cpd: false

filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'

checks:
    php: true
    javascript: true

build:
    environment:
        php: '7.1.6'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=codecoverage'
                coverage:
                    file: 'codecoverage'
                    format: 'clover'
