version: "2"

services:
  database:
    hostname: database
    ports:
      - "3306:3306"
    image: mariadb:latest
    environment:
      - MYSQL_HOST=database
      - MYSQL_PASSWORD=auskunftsbegehren_at
      - MYSQL_USER=auskunftsbegehren_at
      - MYSQL_DATABASE=auskunftsbegehren_at
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - /opt/docker-mariadb:/var/lib/mysql

  importer:
    hostname: importer
    #image: cyber-perikarp/auskunftsbegehren_at_adressen:latest
    build: ../auskunftsbegehren_at_adressen
    environment:
       - MYSQL_HOST=database
       - MYSQL_PASSWORD=auskunftsbegehren_at
       - MYSQL_USER=auskunftsbegehren_at
       - MYSQL_DATABASE=auskunftsbegehren_at
    depends_on:
       - "database"
    links:
       - database:database

  app:
    #image: cyber-perikarp/auskunftsbegehren_at
    build: .
    hostname: webserver
    ports:
     - "8080:80"
    depends_on:
      - "database"
      - "mailcatcher"
    links:
      - database:database
      - mailcatcher:mailcatcher
    volumes:
      - /opt/docker-pdf:/var/pdfStorage

  mailcatcher:
    image: schickling/mailcatcher
    hostname: mailcatcher
    ports:
      - "8081:1080"
    environment:
      - MAILCATCHER_PORT_1025_TCP_ADDR=25

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8082:80
    environment:
       - PMA_HOST=database
       - PMA_PASSWORD=auskunftsbegehren_at
       - PMA_USER=auskunftsbegehren_at
