version: "2"

services:
  app:
    image: cyber-perikarp/auskunftsbegehren_at
    hostname: webserver
    ports:
     - "8080:8080"
    depends_on:
      - "database"
      - "mailcatcher"
      - "dataimport"
    links:
      - database:database
      - mailcatcher:mailcatcher
    restart: unless-stopped

  database:
    image: mariadb:latest
    hostname: dbserver
    environment:
      - MYSQL_PASSWORD=auskunftsbegehren_at
      - MYSQL_USER=auskunftsbegehren_at
      - MYSQL_DATABASE=auskunftsbegehren_at
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped

  mailcatcher:
    image: schickling/mailcatcher
    hostname: mailcatcher
    ports:
      - "8081:1080"
    restart: unless-stopped

  dataimport:

    restart: never